apiVersion: v1
kind: Service
metadata:
  name: auth-user-service
  labels:
    app: auth-user-service
    monitoring: enabled
spec:
  selector:
    app: auth-user-service
  ports:
    - name: http
      port: 8081
      targetPort: 8081
  type: ClusterIP