apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-project
  template:
    metadata:
      labels:
        app: mysql-project
    spec:
      containers:
        - name: mysql-project
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              value: projectdb
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-project-storage
      volumes:
        - name: mysql-project-storage
          persistentVolumeClaim:
            claimName: mysql-project-pvc