apiVersion: v1
kind: Service
metadata:
  name: payments-service
  labels:
    app: payments-service
    monitoring: enabled
spec:
  selector:
    app: payments-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
  type: ClusterIP