apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: notification-service
          image: ghcr.io/javinoves/notification-service:dev
          ports:
            - containerPort: 8085
          env:
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: notification-service-secret
                  key: SPRING_MAIL_USERNAME
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notification-service-secret
                  key: SPRING_MAIL_PASSWORD
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://discovery-server:8761/eureka
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: guest
            - name: SPRING_RABBITMQ_PASSWORD
              value: guest
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"