apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config-server
  - discovery-server
  - auth-user-service
  - notification-service
  - project-service
  - task-service
  - payments-service
  - api-gateway
  - mysql-auth
  - mysql-project
  - mysql-task
  - mysql-payments
  - rabbitmq
  - frontend
  - cronjob-task-reminders
  - postgres-ai
  - ai-service