apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: discovery-server
          image: ghcr.io/javinoves/discovery-server:dev
          ports:
            - containerPort: 8761
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"