apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: taskmanager-dev
resources:
- ../../base
- namespace.yaml
- ingress.yaml
patches:
- path: replicas-patch.yaml
images:
- name: ghcr.io/javinoves/discovery-server
  newTag: 6a553ded1aaacd917fc0c40b0f94b00e42674047
- name: ghcr.io/javinoves/auth-user-service
  newTag: 6a553ded1aaacd917fc0c40b0f94b00e42674047
- name: ghcr.io/javinoves/notification-service
  newTag: 6a553ded1aaacd917fc0c40b0f94b00e42674047
- name: ghcr.io/javinoves/project-service
  newTag: 6a553ded1aaacd917fc0c40b0f94b00e42674047
- name: ghcr.io/javinoves/task-service
  newTag: 6a553ded1aaacd917fc0c40b0f94b00e42674047
- name: ghcr.io/javinoves/payments-service
  newTag: 6a553ded1aaacd917fc0c40b0f94b00e42674047
- name: ghcr.io/javinoves/api-gateway
  newTag: 6a553ded1aaacd917fc0c40b0f94b00e42674047
- name: ghcr.io/javinoves/frontend
  newTag: 6a553ded1aaacd917fc0c40b0f94b00e42674047
- name: ghcr.io/javinoves/ai-service
  newTag: 6a553ded1aaacd917fc0c40b0f94b00e42674047
