apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: taskmanager-dev
resources:
- ../../base
- namespace.yaml
- ingress.yaml
patches:
- path: replicas-patch.yaml
images:
- name: ghcr.io/javinoves/discovery-server
  newTag: 7dea3dc5b1c91cf13e270920aff8be8b8adee7af
- name: ghcr.io/javinoves/auth-user-service
  newTag: 7dea3dc5b1c91cf13e270920aff8be8b8adee7af
- name: ghcr.io/javinoves/notification-service
  newTag: 7dea3dc5b1c91cf13e270920aff8be8b8adee7af
- name: ghcr.io/javinoves/project-service
  newTag: 7dea3dc5b1c91cf13e270920aff8be8b8adee7af
- name: ghcr.io/javinoves/task-service
  newTag: 7dea3dc5b1c91cf13e270920aff8be8b8adee7af
- name: ghcr.io/javinoves/payments-service
  newTag: 7dea3dc5b1c91cf13e270920aff8be8b8adee7af
- name: ghcr.io/javinoves/api-gateway
  newTag: 7dea3dc5b1c91cf13e270920aff8be8b8adee7af
- name: ghcr.io/javinoves/frontend
  newTag: 7dea3dc5b1c91cf13e270920aff8be8b8adee7af
